In [9]:
from sklearn.datasets import fetch_covtype
cov_type = fetch_covtype()

In [10]:
type(cov_type)

sklearn.utils._bunch.Bunch

In [11]:
cov_type.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'feature_names', 'DESCR'])

In [12]:
print(cov_type.DESCR)

.. _covtype_dataset:

Forest covertypes
-----------------

The samples in this dataset correspond to 30×30m patches of forest in the US,
collected for the task of predicting each patch's cover type,
i.e. the dominant species of tree.
There are seven covertypes, making this a multiclass classification problem.
Each sample has 54 features, described on the
`dataset's homepage <https://archive.ics.uci.edu/ml/datasets/Covertype>`__.
Some of the features are boolean indicators,
while others are discrete or continuous measurements.

**Data Set Characteristics:**

=================   ============
Classes                        7
Samples total             581012
Dimensionality                54
Features                     int
=================   ============

:func:`sklearn.datasets.fetch_covtype` will load the covertype dataset;
it returns a dictionary-like 'Bunch' object
with the feature matrix in the ``data`` member
and the target values in ``target``. If optional argument 'as_frame' is
set to 'True', it will return ``data`` and ``target`` as pandas
data frame, and there will be an additional member ``frame`` as well.
The dataset will be downloaded from the web if necessary.

In [13]:
cov_type.data

array([[2.596e+03, 5.100e+01, 3.000e+00, ..., 0.000e+00, 0.000e+00,
        0.000e+00],
       [2.590e+03, 5.600e+01, 2.000e+00, ..., 0.000e+00, 0.000e+00,
        0.000e+00],
       [2.804e+03, 1.390e+02, 9.000e+00, ..., 0.000e+00, 0.000e+00,
        0.000e+00],
       ...,
       [2.386e+03, 1.590e+02, 1.700e+01, ..., 0.000e+00, 0.000e+00,
        0.000e+00],
       [2.384e+03, 1.700e+02, 1.500e+01, ..., 0.000e+00, 0.000e+00,
        0.000e+00],
       [2.383e+03, 1.650e+02, 1.300e+01, ..., 0.000e+00, 0.000e+00,
        0.000e+00]], shape=(581012, 54))

In [14]:
type(cov_type.data)

numpy.ndarray

In [15]:
cov_type.target

array([5, 5, 2, ..., 3, 3, 3], shape=(581012,), dtype=int32)

In [16]:
cov_type.target.shape

(581012,)

In [17]:
cov_type.frame

In [18]:
type(cov_type.frame)

NoneType

In [19]:
cov_type.target_names

['Cover_Type']

In [20]:
cov_type.feature_names

['Elevation',
 'Aspect',
 'Slope',
 'Horizontal_Distance_To_Hydrology',
 'Vertical_Distance_To_Hydrology',
 'Horizontal_Distance_To_Roadways',
 'Hillshade_9am',
 'Hillshade_Noon',
 'Hillshade_3pm',
 'Horizontal_Distance_To_Fire_Points',
 'Wilderness_Area_0',
 'Wilderness_Area_1',
 'Wilderness_Area_2',
 'Wilderness_Area_3',
 'Soil_Type_0',
 'Soil_Type_1',
 'Soil_Type_2',
 'Soil_Type_3',
 'Soil_Type_4',
 'Soil_Type_5',
 'Soil_Type_6',
 'Soil_Type_7',
 'Soil_Type_8',
 'Soil_Type_9',
 'Soil_Type_10',
 'Soil_Type_11',
 'Soil_Type_12',
 'Soil_Type_13',
 'Soil_Type_14',
 'Soil_Type_15',
 'Soil_Type_16',
 'Soil_Type_17',
 'Soil_Type_18',
 'Soil_Type_19',
 'Soil_Type_20',
 'Soil_Type_21',
 'Soil_Type_22',
 'Soil_Type_23',
 'Soil_Type_24',
 'Soil_Type_25',
 'Soil_Type_26',
 'Soil_Type_27',
 'Soil_Type_28',
 'Soil_Type_29',
 'Soil_Type_30',
 'Soil_Type_31',
 'Soil_Type_32',
 'Soil_Type_33',
 'Soil_Type_34',
 'Soil_Type_35',
 'Soil_Type_36',
 'Soil_Type_37',
 'Soil_Type_38',
 'Soil_Type_39']

In [21]:
len(cov_type.feature_names)

54

In [22]:
import pandas as pd

In [26]:
df_cov_type = pd.DataFrame(data=cov_type.data, columns=cov_type.feature_names)
print("first few rows of the Forest Covertypes Dataset:")
df_cov_type

first few rows of the Forest Covertypes Dataset:

,Elevation,Aspect,Slope,Horizontal_Distance_To_Hydrology,Vertical_Distance_To_Hydrology,Horizontal_Distance_To_Roadways,Hillshade_9am,Hillshade_Noon,Hillshade_3pm,Horizontal_Distance_To_Fire_Points,...,Soil_Type_30,Soil_Type_31,Soil_Type_32,Soil_Type_33,Soil_Type_34,Soil_Type_35,Soil_Type_36,Soil_Type_37,Soil_Type_38,Soil_Type_39
0,2596.0,51.0,3.0,258.0,0.0,510.0,221.0,232.0,148.0,6279.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2590.0,56.0,2.0,212.0,-6.0,390.0,220.0,235.0,151.0,6225.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,2804.0,139.0,9.0,268.0,65.0,3180.0,234.0,238.0,135.0,6121.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,2785.0,155.0,18.0,242.0,118.0,3090.0,238.0,238.0,122.0,6211.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,2595.0,45.0,2.0,153.0,-1.0,391.0,220.0,234.0,150.0,6172.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
581007,2396.0,153.0,20.0,85.0,17.0,108.0,240.0,237.0,118.0,837.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
581008,2391.0,152.0,19.0,67.0,12.0,95.0,240.0,237.0,119.0,845.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
581009,2386.0,159.0,17.0,60.0,7.0,90.0,236.0,241.0,130.0,854.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
581010,2384.0,170.0,15.0,60.0,5.0,90.0,230.0,245.0,143.0,864.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
581011,2383.0,165.0,13.0,60.0,4.0,67.0,231.0,244.0,141.0,875.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [28]:
df_cov_type[[col for col in df_cov_type.columns if 'Soil_Type' in col]].describe()

,Soil_Type_0,Soil_Type_1,Soil_Type_2,Soil_Type_3,Soil_Type_4,Soil_Type_5,Soil_Type_6,Soil_Type_7,Soil_Type_8,Soil_Type_9,...,Soil_Type_30,Soil_Type_31,Soil_Type_32,Soil_Type_33,Soil_Type_34,Soil_Type_35,Soil_Type_36,Soil_Type_37,Soil_Type_38,Soil_Type_39
count,581012.000000,581012.000000,581012.000000,581012.000000,581012.000000,581012.000000,581012.000000,581012.000000,581012.000000,581012.000000,...,581012.000000,581012.000000,581012.000000,581012.000000,581012.000000,581012.000000,581012.000000,581012.000000,581012.000000,581012.000000
mean,0.005217,0.012952,0.008301,0.021335,0.002749,0.011316,0.000181,0.000308,0.001974,0.056168,...,0.044175,0.090392,0.077716,0.002773,0.003255,0.000205,0.000513,0.026803,0.023762,0.015060
std,0.072039,0.113066,0.090731,0.144499,0.052356,0.105775,0.013442,0.017550,0.044387,0.230245,...,0.205483,0.286743,0.267725,0.052584,0.056957,0.014310,0.022641,0.161508,0.152307,0.121791
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [29]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report
import numpy as np
from sklearn.neighbors import KNeighborsClassifier

In [30]:
X, y = cov_type.data, cov_type.target
print(f"Features shape: {X.shape}")
print(f"Target shape: {y.shape}")

Features shape: (581012, 54)
Target shape: (581012,)

In [32]:
#training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.05, random_state=355)

In [33]:
print(f"X_train shape: {X_train.shape}")
print(f"y_train shape: {y_train.shape}")
print(f"X_test shape: {X_test.shape}")
print(f"y_test shape: {y_test.shape}")

X_train shape: (551961, 54)
y_train shape: (551961,)
X_test shape: (29051, 54)
y_test shape: (29051,)

In [35]:
#Initialize and train
kn_classifier = KNeighborsClassifier(n_neighbors=5)
kn_classifier.fit(X_train, y_train)

KNeighborsClassifier()

In [41]:
import time
start_time = time.time()
y_pred = kn_classifier.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy:.2f}")
unique_labels = np.unique(y)
target_names = [f"Class {label}" for label in unique_labels]
print("\nClassification Report:") 
print(classification_report(y_test, y_pred, target_names=target_names))
print(f"nTotal time taken: {time.time() - start_time:.4f} seconds")

Accuracy: 0.97

Classification Report:
              precision    recall  f1-score   support

     Class 1       0.97      0.97      0.97     10567
     Class 2       0.98      0.98      0.98     14184
     Class 3       0.95      0.97      0.96      1770
     Class 4       0.95      0.78      0.85       158
     Class 5       0.94      0.92      0.93       467
     Class 6       0.96      0.94      0.95       914
     Class 7       0.97      0.98      0.98       991

    accuracy                           0.97     29051
   macro avg       0.96      0.93      0.95     29051
weighted avg       0.97      0.97      0.97     29051

nTotal time taken: 91.8672 seconds

In [43]:
import cudf
from cuml import KNeighborsClassifier as cuKNN
from dask.distributed import Client, LocalCluster 
n_workers = 4 
cluster = LocalCluster(n_workers=n_workers)
client = Client(cluster)
X = cudf.DataFrame(cov_type.data, columns=cov_type.feature_names)
y = cudf.Series(cov_type.target) 
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.05, random_state=355)

/opt/conda/envs/ml_env/lib/python3.11/site-packages/distributed/node.py:187: UserWarning: Port 8787 is already in use.
Perhaps you already have a cluster running?
Hosting the HTTP server on port 34821 instead
  warnings.warn(

In [45]:
kn_classifier_cuml = cuKNN(n_neighbors=5)
kn_classifier_cuml.fit(X_train, y_train)

KNeighborsClassifier()

In [47]:
import time
start_time = time.time()
y_pred = kn_classifier_cuml.predict(X_test)
accuracy = accuracy_score(y_test.to_cupy().get(), y_pred.to_cupy().get())
print(f"Accuracy: {accuracy:.2f}")
y_test_np = y_test.to_numpy()
y_pred_np = y_pred.to_numpy()
unique_labels = np.unique(y_test_np) 
target_names = [f"Class {label}" for label in unique_labels] 
print("\nClassification Report:")
print(classification_report(y_test_np, y_pred_np, target_names=target_names))
client.close()
cluster.close()
print(f"nTotal time taken: {time.time()-start_time:.4f} seconds")

Accuracy: 0.97

Classification Report:
              precision    recall  f1-score   support

     Class 1       0.97      0.97      0.97     10567
     Class 2       0.98      0.98      0.98     14184
     Class 3       0.95      0.97      0.96      1770
     Class 4       0.95      0.78      0.85       158
     Class 5       0.94      0.92      0.93       467
     Class 6       0.96      0.94      0.95       914
     Class 7       0.97      0.98      0.98       991

    accuracy                           0.97     29051
   macro avg       0.96      0.93      0.95     29051
weighted avg       0.97      0.97      0.97     29051

nTotal time taken: 0.6138 seconds

In [49]:
import cudf
import numpy as np
from cuml.neighbors import KNeighborsClassifier
from cuml.model_selection import train_test_split
from cuml.metrics import accuracy_score

# Convert data to cuDF DataFrames for GPU processing and ensure float32 dtype
X = cudf.DataFrame(cov_type.data, columns=cov_type.feature_names).astype('float32')
y = cudf.Series(cov_type.target)

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.05, random_state=355)

# Define the parameter space for KNN
param_dist = {
    'n_neighbors': np.arange(1, 21, dtype=int),
    'p': [1, 2],  # 1 for Manhattan distance, 2 for Euclidean distance
}

# Function to perform k-fold cross-validation with batched prediction
def cross_validate(X, y, model, n_splits=3, batch_size=10000):
    fold_size = np.min([len(X),20000]) // n_splits
    scores = []
    for i in range(n_splits):
        start = i * fold_size
        end = (i + 1) * fold_size
        X_val = X.iloc[start:end]
        y_val = y.iloc[start:end]
        X_train = cudf.concat([X.iloc[:start], X.iloc[end:]])
        y_train = cudf.concat([y.iloc[:start], y.iloc[end:]])
        
        model.fit(X_train, y_train)
        
        # Batched prediction
        y_pred = cudf.Series()
        for j in range(0, len(X_val), batch_size):
            X_batch = X_val.iloc[j:j+batch_size]
            y_pred = cudf.concat([y_pred, model.predict(X_batch)])
        
        score = accuracy_score(y_val, y_pred)
        scores.append(score)
    return np.mean(scores)

# Perform manual randomized search
n_iter = 10
best_score = 0
best_params = {}

for _ in range(n_iter):
    params = {k: np.random.choice(v) for k, v in param_dist.items()}
    knn = KNeighborsClassifier(metric='minkowski', **params)
    score = cross_validate(X_train, y_train, knn)
    
    if score > best_score:
        best_score = score
        best_params = params
    
    print(f"Iteration {_+1}/{n_iter} - Score: {score:.4f} - Params: {params}")

print("Best parameters found:")
for param, value in best_params.items():
    print(f"{param}: {value}")

# Train the best model on the full training set
best_knn = KNeighborsClassifier(**best_params)
best_knn.fit(X_train, y_train)

# Make predictions on the test set in batches
batch_size = 10000
y_pred = cudf.Series()
for i in range(0, len(X_test), batch_size):
    X_batch = X_test.iloc[i:i+batch_size]
    y_pred = cudf.concat([y_pred, best_knn.predict(X_batch)])

# Calculate accuracy
accuracy = accuracy_score(y_test, y_pred)
print(f"\nBest model accuracy: {accuracy:.4f}")

Iteration 1/10 - Score: 0.9686 - Params: {'n_neighbors': np.int64(11), 'p': np.int64(1)}
Iteration 2/10 - Score: 0.9680 - Params: {'n_neighbors': np.int64(9), 'p': np.int64(2)}
Iteration 3/10 - Score: 0.9598 - Params: {'n_neighbors': np.int64(15), 'p': np.int64(2)}
Iteration 4/10 - Score: 0.9680 - Params: {'n_neighbors': np.int64(9), 'p': np.int64(2)}
Iteration 5/10 - Score: 0.9709 - Params: {'n_neighbors': np.int64(6), 'p': np.int64(1)}
Iteration 6/10 - Score: 0.9603 - Params: {'n_neighbors': np.int64(17), 'p': np.int64(1)}
Iteration 7/10 - Score: 0.9705 - Params: {'n_neighbors': np.int64(6), 'p': np.int64(2)}
Iteration 8/10 - Score: 0.9620 - Params: {'n_neighbors': np.int64(16), 'p': np.int64(1)}
Iteration 9/10 - Score: 0.9705 - Params: {'n_neighbors': np.int64(6), 'p': np.int64(2)}
Iteration 10/10 - Score: 0.9710 - Params: {'n_neighbors': np.int64(3), 'p': np.int64(2)}
Best parameters found:
n_neighbors: 3
p: 2

Best model accuracy: 0.9719

In [53]:
# Save the best model
import pickle as pkl
with open("best_knn_model.pkl", "wb") as f:
    pkl.dump(best_knn, f)